spring:
  application:
    name: oauth2-client
  security:
    oauth2:
      client:

        registration:
          oidc-client:
            client-id: nbs
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
            scope: openid
        provider:
          oidc-client:
            issuer-uri: http://localhost:9000



